name: Workflow with parameters
on:
  workflow_dispatch:
    inputs:
      env_param:
        description: 'Environment to deploy'
        required: true
      change_id:
        description: 'Change Reference'
        required: true
        
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event.inputs.env_param}} ${{github.event.inputs.change_id}}"
