run-name: Workflow with parameters ${{inputs.env_param}} and ${{inputs.change_id}}
on:
  workflow_dispatch:
    inputs:
      env_param:
        type: choice
        description: 'Environment to deploy'
        options:
        - Production
        - Test 1
        - Test 2
        - Development 1
        - Development 2        
        required: true
      change_id:
        description: 'Change Reference'
        required: true
        
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event.inputs.env_param}} ${{github.event.inputs.change_id}}"
